version: '3.6'

services:
    splunk:
        image: splunk/splunk:latest
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=${SPLUNK_TOKENZ}
            - SPLUNK_APPS_URL=https://github.com/splunk/ethereum-basics/releases/download/latest/ethereum-basics.tgz
        ports:
            - 18000:8000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
            - /opt/splunk/var
            - /opt/splunk/etc
    ethlogger:
        image: splunkdlt/ethlogger:latest
        container_name: ethlogger
        environment:
            - COLLECT_PEER_INFO=true
            - COLLECT_PENDING_TX=true
            - ETH_RPC_URL=http://besu:8545
            - NETWORK_NAME=/genesis.json
            # Use these environment variables to connect to infura
            # - ETH_RPC_URL=https://mainnet.infura.io/v3/<your infura project id>
            # - NETWORK_NAME=mainnet
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - ABI_DIR=/app/abis
            - DEBUG=ethlogger:platforms,ethlogger:eth
        volumes:
            - ./abis:/app/abis
            - ./:/app
        depends_on:
            - splunk
        restart: always
    besu:
        image: hyperledger/besu:1.4.6
        container_name: besu
        environment:
            - BESU_PUBLIC_KEY_DIRECTORY=/opt/besu/public-keys/
            - BESU_P2P_HOST=0.0.0.0
            - BESU_RPC_HTTP_ENABLED=true
            - BESU_RPC_WS_ENABLED=true
            - BESU_NETWORK=/genesis.json
            - BESU_MINER_ENABLED=false
            - BESU_HOST_WHITELIST="*"
            - BESU_RPC_HTTP_HOST=0.0.0.0
            - BESU_RPC_WS_HOST=0.0.0.0
            - BESU_RPC_HTTP_API=admin,eth,debug,net,txpool,trace,web3
            - BESU_RPC_HTTP_CORS_ORIGIN="all"
            - BESU_LOGGING=debug
            # Splunk logging configuration
            - LOGGER=Splunk
            - SPLUNK_URL=https://splunk:8088
            - SPLUNK_INDEX=logs
            - SPLUNK_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_SKIPTLSVERIFY=true
